In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('a.csv',encoding="cp1252")

In [4]:
df.head()

,#,SO Number,Document Internal ID,Posting Date,Execution Date,Customer Name,ItemName,Pending Qty,Unit Amt,Total Amt,Pending Days,Status,Sales Employee Name,SO Pending,Order Branch Name,Aging Range
0,1,6004,89728,07/20/2019,07/20/2019,MAHINDRA & MAHINDRA LIMITED,Installation Charges,1.0,20000.0,20000.0,688.0,NaN,Pankaj,Other Reason,Mumbai,>15 Days
1,2,8761,92651,09/06/2019,07/31/2021,VOLTEK ENGINEERING,LIEBERT 5 KVA LXI UPS,1.0,330000.0,330000.0,640.0,SO Pending for Material not -LIEBERT 5 KVA LXI...,Amar chavan,SO Pending for Material not available,Mumbai,>15 Days
2,3,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
3,4,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
4,5,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days

In [5]:
pv = df.pivot_table(values=['Total Amt'] , index=['Sales Employee Name' , 'Pending Days'] , columns=['Aging Range'], aggfunc=np.mean)
pv

                                     Total Amt
Aging Range                          >15  Days >7  Days
Sales Employee Name Pending Days
AJITH KHEDEKAR      297.0         21415.845000      NaN
                    308.0         30734.600000      NaN
Abhishek Nagda      3.0                    NaN   1150.0
                    17.0           2564.550000      NaN
                    19.0          21562.800000      NaN
...                                        ...      ...
Umesh Sawakhande    7.0                    NaN   5289.9
                    104.0          3114.360000      NaN
Vinod KK            49.0            989.200000      NaN
                    66.0            422.500000      NaN
                    82.0           4009.014634      NaN

[155 rows x 2 columns]

In [6]:
pv

                                     Total Amt
Aging Range                          >15  Days >7  Days
Sales Employee Name Pending Days
AJITH KHEDEKAR      297.0         21415.845000      NaN
                    308.0         30734.600000      NaN
Abhishek Nagda      3.0                    NaN   1150.0
                    17.0           2564.550000      NaN
                    19.0          21562.800000      NaN
...                                        ...      ...
Umesh Sawakhande    7.0                    NaN   5289.9
                    104.0          3114.360000      NaN
Vinod KK            49.0            989.200000      NaN
                    66.0            422.500000      NaN
                    82.0           4009.014634      NaN

[155 rows x 2 columns]

In [7]:
pv.append(pd.Series(name=('','')))

/home/prabhat/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.

                                     Total Amt
Aging Range                          >15  Days >7  Days
Sales Employee Name Pending Days
AJITH KHEDEKAR      297.0         21415.845000      NaN
                    308.0         30734.600000      NaN
Abhishek Nagda      3.0                    NaN   1150.0
                    17.0           2564.550000      NaN
                    19.0          21562.800000      NaN
...                                        ...      ...
Umesh Sawakhande    104.0          3114.360000      NaN
Vinod KK            49.0            989.200000      NaN
                    66.0            422.500000      NaN
                    82.0           4009.014634      NaN
                                           NaN      NaN

[156 rows x 2 columns]

In [8]:
pv.index

MultiIndex([(  'AJITH KHEDEKAR', 297.0),
            (  'AJITH KHEDEKAR', 308.0),
            (  'Abhishek Nagda',   3.0),
            (  'Abhishek Nagda',  17.0),
            (  'Abhishek Nagda',  19.0),
            (  'Abhishek Nagda',  31.0),
            (     'Amar chavan',   3.0),
            (     'Amar chavan',   5.0),
            (     'Amar chavan',  80.0),
            (     'Amar chavan',  83.0),
            ...
            (     'Sagar Kemse', 101.0),
            (     'Sagar Kemse', 133.0),
            (  'Sunny Kothmire', 131.0),
            (  'Sunny Kothmire', 468.0),
            ('Umesh Sawakhande',   3.0),
            ('Umesh Sawakhande',   7.0),
            ('Umesh Sawakhande', 104.0),
            (        'Vinod KK',  49.0),
            (        'Vinod KK',  66.0),
            (        'Vinod KK',  82.0)],
           names=['Sales Employee Name', 'Pending Days'], length=155)

In [9]:
pv.columns

MultiIndex([('Total Amt', '>15  Days'),
            ('Total Amt',  '>7  Days')],
           names=[None, 'Aging Range'])

In [10]:
pv["Grand total"] = pv.sum(axis = 1)

In [11]:
pv

                                     Total Amt            Grand total
Aging Range                          >15  Days >7  Days
Sales Employee Name Pending Days
AJITH KHEDEKAR      297.0         21415.845000      NaN  21415.845000
                    308.0         30734.600000      NaN  30734.600000
Abhishek Nagda      3.0                    NaN   1150.0   1150.000000
                    17.0           2564.550000      NaN   2564.550000
                    19.0          21562.800000      NaN  21562.800000
...                                        ...      ...           ...
Umesh Sawakhande    7.0                    NaN   5289.9   5289.900000
                    104.0          3114.360000      NaN   3114.360000
Vinod KK            49.0            989.200000      NaN    989.200000
                    66.0            422.500000      NaN    422.500000
                    82.0           4009.014634      NaN   4009.014634

[155 rows x 3 columns]

In [12]:
p2 = pv.sum(axis = 0)
print(p2)
k=pd.DataFrame(p2)

             Aging Range
Total Amt    >15  Days      4.993077e+07
             >7  Days       8.927650e+06
Grand total                 5.885842e+07
dtype: float64

In [13]:
temp_df = pd.DataFrame(data=[p2],
                       columns=list(pv.columns), index = pv.index)
temp_df

s = pd.Series(name=("", "Grand total"))
pv = pv.append(pd.Series(name=("", "Grand total")))

/home/prabhat/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """
/home/prabhat/.local/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [14]:
pv

                                     Total Amt            Grand total
Aging Range                          >15  Days >7  Days
Sales Employee Name Pending Days
AJITH KHEDEKAR      297.0         21415.845000      NaN  21415.845000
                    308.0         30734.600000      NaN  30734.600000
Abhishek Nagda      3.0                    NaN   1150.0   1150.000000
                    17.0           2564.550000      NaN   2564.550000
                    19.0          21562.800000      NaN  21562.800000
...                                        ...      ...           ...
Umesh Sawakhande    104.0          3114.360000      NaN   3114.360000
Vinod KK            49.0            989.200000      NaN    989.200000
                    66.0            422.500000      NaN    422.500000
                    82.0           4009.014634      NaN   4009.014634
                    Grand total            NaN      NaN           NaN

[156 rows x 3 columns]

In [15]:
pv[pv.columns[3]][-1] = 23.0

IndexError: index 3 is out of bounds for axis 0 with size 3

In [182]:
pv

                                                                    PO Number  \
ageing                                                            0 to 1 Days
Sales Employee Name Vendor Name
ASIF SHAIKH         ULTRATECH CEMENT LTD                                  1.0
Amar chavan         SCHNEIDER ELECTRIC INDIA PVT LTD                      NaN
Asmita              NOCIL LIMITED                                         NaN
                    ULTRATECH CEMENT LTD                                  5.0
Deven Gada          BHILOSA INDUSTRIES PRIVATE LIMITED                    1.0
Neeta               INTELLIGENCE BUREAU                                   1.0
POONAM KAMBLE       OBEROI CONSTRUCTIONS LIMITED                          NaN
PRASAD BASETTY      MAHARASHTRA BORDER CHECK POST NETWORK LIMITED         1.0
Rajiv Nambiar       AVENUE SUPERMARTS LTD                                 NaN
                    CHOKSEY CHEMICAL PVT LTD                              1.0
                    COMTEL INFOSYSTEMS PVT LTD                            NaN
                    DR FAROOQUI POLYCLINIC                                1.0
                    ENCOMPASS EVENTS PVT LTD                              NaN
                    SIMI ELECTRONICS                                      1.0
                    TEAM ONE TECH SOLUTIONS LLP                           1.0
                    TRIP JACK PRIVATE LIMITED                             1.0
Sachin Badkar       SAPAT GLOBAL HEALTH  PVT LTD                          1.0
Sachin Kamble       AVENUE SUPERMARTS LTD                                 1.0
                    Grand total                                          16.0

                                                                               \
ageing                                                            2 to 4 Days
Sales Employee Name Vendor Name
ASIF SHAIKH         ULTRATECH CEMENT LTD                                  NaN
Amar chavan         SCHNEIDER ELECTRIC INDIA PVT LTD                      NaN
Asmita              NOCIL LIMITED                                         1.0
                    ULTRATECH CEMENT LTD                                  NaN
Deven Gada          BHILOSA INDUSTRIES PRIVATE LIMITED                    NaN
Neeta               INTELLIGENCE BUREAU                                   NaN
POONAM KAMBLE       OBEROI CONSTRUCTIONS LIMITED                          NaN
PRASAD BASETTY      MAHARASHTRA BORDER CHECK POST NETWORK LIMITED         NaN
Rajiv Nambiar       AVENUE SUPERMARTS LTD                                 NaN
                    CHOKSEY CHEMICAL PVT LTD                              NaN
                    COMTEL INFOSYSTEMS PVT LTD                            1.0
                    DR FAROOQUI POLYCLINIC                                NaN
                    ENCOMPASS EVENTS PVT LTD                              1.0
                    SIMI ELECTRONICS                                      NaN
                    TEAM ONE TECH SOLUTIONS LLP                           NaN
                    TRIP JACK PRIVATE LIMITED                             NaN
Sachin Badkar       SAPAT GLOBAL HEALTH  PVT LTD                          NaN
Sachin Kamble       AVENUE SUPERMARTS LTD                                 NaN
                    Grand total                                           3.0

                                                                               \
ageing                                                            5 to 7 Days
Sales Employee Name Vendor Name
ASIF SHAIKH         ULTRATECH CEMENT LTD                                  NaN
Amar chavan         SCHNEIDER ELECTRIC INDIA PVT LTD                      1.0
Asmita              NOCIL LIMITED                                         NaN
                    ULTRATECH CEMENT LTD                                  1.0
Deven Gada          BHILOSA INDUSTRIES PRIVATE LIMITED                    NaN
Neeta               INTELLIGENCE BUREAU                                   NaN
POONAM KAMBLE       OBEROI CONSTRUCTIONS LIMITED                          1.0
PRASAD BASETTY      MAHARASHTRA BORDER CHECK POST NETWORK LIMITED         NaN
Rajiv Nambiar       AVENUE SUPERMARTS LTD                                 1.0
                    CHOKSEY CHEMICAL PVT LTD                              NaN
                    COMTEL INFOSYSTEMS PVT LTD                            NaN
                    DR FAROOQUI POLYCLINIC                                NaN
                    ENCOMPASS EVENTS PVT LTD                              NaN
                    SIMI ELECTRONICS                                      NaN
                    TEAM ONE TECH SOLUTIONS LLP                           NaN
                    TRIP JACK PRIVATE LIMITED                             NaN
Sachin Badkar       SAPAT GLOBAL HEALTH  PVT LTD                          NaN
Sachin Kamble       AVENUE SUPERMARTS LTD                                 NaN
                    Grand total                                           4.0

                                                                  Grand total
ageing
Sales Employee Name Vendor Name
ASIF SHAIKH         ULTRATECH CEMENT LTD                                  1.0
Amar chavan         SCHNEIDER ELECTRIC INDIA PVT LTD                      1.0
Asmita              NOCIL LIMITED                                         1.0
                    ULTRATECH CEMENT LTD                                  6.0
Deven Gada          BHILOSA INDUSTRIES PRIVATE LIMITED                    1.0
Neeta               INTELLIGENCE BUREAU                                   1.0
POONAM KAMBLE       OBEROI CONSTRUCTIONS LIMITED                          1.0
PRASAD BASETTY      MAHARASHTRA BORDER CHECK POST NETWORK LIMITED         1.0
Rajiv Nambiar       AVENUE SUPERMARTS LTD                                 1.0
                    CHOKSEY CHEMICAL PVT LTD                              1.0
                    COMTEL INFOSYSTEMS PVT LTD                            1.0
                    DR FAROOQUI POLYCLINIC                                1.0
                    ENCOMPASS EVENTS PVT LTD                              1.0
                    SIMI ELECTRONICS                                      1.0
                    TEAM ONE TECH SOLUTIONS LLP                           1.0
                    TRIP JACK PRIVATE LIMITED                             1.0
Sachin Badkar       SAPAT GLOBAL HEALTH  PVT LTD                          1.0
Sachin Kamble       AVENUE SUPERMARTS LTD                                 1.0
                    Grand total                                          23.0

In [183]:
pv.to_excel('b.xls')

<ipython-input-183-0d9997b5347a>:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  pv.to_excel('b.xls')

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('a.csv')

In [7]:
df

,#,SBU - Head,SBU - Department,Document Entry,PO Number,PRF NO,Line Status,Canceled,Vendor Code,Vendor Name,...,Total Days,ageing,Target Days,Order Branch Name,Payment Terms Code,Part Code,Expected Date of Delivery,BuyBack delay,Remarks,Aging Range
0,1,NaN,PWR-BTRY,60318,75063,75322.0,O,N,S14470,BHILOSA INDUSTRIES PRIVATE LIMITED,...,1,0 to 1 Days,-5.0,Vapi,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 75322.,>7 Days
1,3,NaN,PWR-BTRY,60333,1495,3946.0,O,N,S20248,CHOKSEY CHEMICAL PVT LTD,...,1,0 to 1 Days,-5.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3946.,>7 Days
2,4,NaN,PWR-BTRY,60348,1510,3958.0,O,N,S22574,DR FAROOQUI POLYCLINIC,...,1,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3958.,>7 Days
3,11,NaN,PWR-BTRY,60427,1584,4108.0,O,N,S11146,SIMI ELECTRONICS,...,1,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,NaN,Based On Sales Quotations 4108.,>7 Days
4,29,NaN,PWR-BTRY,60506,1662,4367.0,O,N,S22585,TRIP JACK PRIVATE LIMITED,...,1,0 to 1 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,06/08/2021,NaN,Based On Sales Quotations 4367.,>7 Days
5,6,NaN,PWR-BTRY,60374,1531,4040.0,O,N,S19423,NOCIL LIMITED,...,2,2 to 4 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4040.,>7 Days
6,14,NaN,PWR-BTRY,60457,1614,4238.0,O,N,S19711,COMTEL INFOSYSTEMS PVT LTD,...,3,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/04/2021,NaN,Based On Sales Quotations 4238.,>7 Days
7,7,NaN,PWR-BTRY,60389,1546,4027.0,O,N,S19854,ENCOMPASS EVENTS PVT LTD,...,4,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,NaN,Based On Sales Quotations 4027.,>7 Days
8,5,NaN,PWR-BTRY,60360,1519,4010.0,O,N,S12943,AVENUE SUPERMARTS LTD,...,5,5 to 7 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,05/27/2021,NaN,Based On Sales Quotations 4010.,>7 Days
9,2,NaN,PWR-BTRY,60328,1490,3611.0,O,N,S22112,SCHNEIDER ELECTRIC INDIA PVT LTD,...,7,5 to 7 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,11/30/2020,Delivery Pending,Based On Sales Quotations 3611.,>7 Days
10,15,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,ULTRATECH CEMENT LTD,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
11,16,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,ULTRATECH CEMENT LTD,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
12,20,NaN,PWR-BTRY,60486,1642,4313.0,O,N,S12876,OBEROI CONSTRUCTIONS LIMITED,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/12/2021,Delivery Pending,Based On Sales Quotations 4313.,>7 Days
13,8,NaN,PWR-BTRY,60392,1549,4095.0,O,N,S12943,AVENUE SUPERMARTS LTD,...,0,0 to 1 Days,-4.0,Pune,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4095.,>7 Days
14,9,NaN,PWR-BTRY,60393,1550,4096.0,O,N,S22579,SAPAT GLOBAL HEALTH PVT LTD,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,Delivery Pending,Based On Sales Quotations 4096.,>7 Days
15,10,NaN,PWR-BTRY,60403,1560,4138.0,O,N,S22536,MAHARASHTRA BORDER CHECK POST NETWORK LIMITED,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4138.,>7 Days
16,12,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
17,13,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
18,17,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
19,18,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
20,19,NaN,PWR-BTRY,60485,1641,4311.0,O,N,S22584,INTELLIGENCE BUREAU,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4311.,>7 Days
21,21,NaN,PWR-UPS,60497,1653,4352.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
22,22,NaN,PWR-BTRY,60497,1653,4352.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
23,23,NaN,PWR-UPS,60498,1654,4353.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
24,24,NaN,PWR-BTRY,60498,1654,4353.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
25,25,NaN,PWR-UPS,60500,1656,4359.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
26,26,NaN,PWR-BTRY,60500,1656,4359.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
27,27,NaN,PWR-UPS,60501,1657,4364.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
28,28,NaN,PWR-BTRY,60501,1657,4364.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
29,30,NaN,NaN,60516,1672,NaN,O,N,S22462,TEAM ONE TECH SOLUTIONS LLP,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/07/2021,NaN,Based On Sales Quotations 4315.,>7 Days

In [ ]:
#experimental

In [4]:
df.insert(1,"New", 100)
df

,#,New,SBU - Head,SBU - Department,Document Entry,PO Number,PRF NO,Line Status,Canceled,Vendor Code,...,Total Days,ageing,Target Days,Order Branch Name,Payment Terms Code,Part Code,Expected Date of Delivery,BuyBack delay,Remarks,Aging Range
0,1,100,NaN,PWR-BTRY,60318,75063,75322.0,O,N,S14470,...,1,0 to 1 Days,-5.0,Vapi,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 75322.,>7 Days
1,3,100,NaN,PWR-BTRY,60333,1495,3946.0,O,N,S20248,...,1,0 to 1 Days,-5.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3946.,>7 Days
2,4,100,NaN,PWR-BTRY,60348,1510,3958.0,O,N,S22574,...,1,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3958.,>7 Days
3,11,100,NaN,PWR-BTRY,60427,1584,4108.0,O,N,S11146,...,1,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,NaN,Based On Sales Quotations 4108.,>7 Days
4,29,100,NaN,PWR-BTRY,60506,1662,4367.0,O,N,S22585,...,1,0 to 1 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,06/08/2021,NaN,Based On Sales Quotations 4367.,>7 Days
5,6,100,NaN,PWR-BTRY,60374,1531,4040.0,O,N,S19423,...,2,2 to 4 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4040.,>7 Days
6,14,100,NaN,PWR-BTRY,60457,1614,4238.0,O,N,S19711,...,3,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/04/2021,NaN,Based On Sales Quotations 4238.,>7 Days
7,7,100,NaN,PWR-BTRY,60389,1546,4027.0,O,N,S19854,...,4,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,NaN,Based On Sales Quotations 4027.,>7 Days
8,5,100,NaN,PWR-BTRY,60360,1519,4010.0,O,N,S12943,...,5,5 to 7 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,05/27/2021,NaN,Based On Sales Quotations 4010.,>7 Days
9,2,100,NaN,PWR-BTRY,60328,1490,3611.0,O,N,S22112,...,7,5 to 7 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,11/30/2020,Delivery Pending,Based On Sales Quotations 3611.,>7 Days
10,15,100,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
11,16,100,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
12,20,100,NaN,PWR-BTRY,60486,1642,4313.0,O,N,S12876,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/12/2021,Delivery Pending,Based On Sales Quotations 4313.,>7 Days
13,8,100,NaN,PWR-BTRY,60392,1549,4095.0,O,N,S12943,...,0,0 to 1 Days,-4.0,Pune,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4095.,>7 Days
14,9,100,NaN,PWR-BTRY,60393,1550,4096.0,O,N,S22579,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,Delivery Pending,Based On Sales Quotations 4096.,>7 Days
15,10,100,NaN,PWR-BTRY,60403,1560,4138.0,O,N,S22536,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4138.,>7 Days
16,12,100,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
17,13,100,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
18,17,100,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
19,18,100,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
20,19,100,NaN,PWR-BTRY,60485,1641,4311.0,O,N,S22584,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4311.,>7 Days
21,21,100,NaN,PWR-UPS,60497,1653,4352.0,O,N,S10639,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
22,22,100,NaN,PWR-BTRY,60497,1653,4352.0,O,N,S10639,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
23,23,100,NaN,PWR-UPS,60498,1654,4353.0,O,N,S10639,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
24,24,100,NaN,PWR-BTRY,60498,1654,4353.0,O,N,S10639,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
25,25,100,NaN,PWR-UPS,60500,1656,4359.0,O,N,S10639,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
26,26,100,NaN,PWR-BTRY,60500,1656,4359.0,O,N,S10639,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
27,27,100,NaN,PWR-UPS,60501,1657,4364.0,O,N,S10639,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
28,28,100,NaN,PWR-BTRY,60501,1657,4364.0,O,N,S10639,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
29,30,100,NaN,NaN,60516,1672,NaN,O,N,S22462,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/07/2021,NaN,Based On Sales Quotations 4315.,>7 Days

In [107]:
df["SBU - Department"].dtype == 'object'

True

In [115]:
a = "(#Total Days#+2)*#PO Number#"

In [116]:
a

0     3
1     3
2     3
3     3
4     3
5     4
6     5
7     6
8     7
9     9
10    9
11    9
12    9
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
Name: Total Days, dtype: int64

In [119]:
a * df["PO Number"]

0     225189
1       4485
2       4530
3       4752
4       4986
5       6124
6       8070
7       9276
8      10633
9      13410
10     14679
11     14679
12     14778
13      3098
14      3100
15      3120
16      3214
17      3214
18      3264
19      3264
20      3282
21      3306
22      3306
23      3308
24      3308
25      3312
26      3312
27      3314
28      3314
29      3344
dtype: int64

# COLUMN OPERATIONS

### Add

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('a.csv')

In [3]:
df.head()

,#,SBU - Head,SBU - Department,Document Entry,PO Number,PRF NO,Line Status,Canceled,Vendor Code,Vendor Name,...,Total Days,ageing,Target Days,Order Branch Name,Payment Terms Code,Part Code,Expected Date of Delivery,BuyBack delay,Remarks,Aging Range
0,1,NaN,PWR-BTRY,60318,75063,75322.0,O,N,S14470,BHILOSA INDUSTRIES PRIVATE LIMITED,...,1,0 to 1 Days,-5.0,Vapi,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 75322.,>7 Days
1,3,NaN,PWR-BTRY,60333,1495,3946.0,O,N,S20248,CHOKSEY CHEMICAL PVT LTD,...,1,0 to 1 Days,-5.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3946.,>7 Days
2,4,NaN,PWR-BTRY,60348,1510,3958.0,O,N,S22574,DR FAROOQUI POLYCLINIC,...,1,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3958.,>7 Days
3,11,NaN,PWR-BTRY,60427,1584,4108.0,O,N,S11146,SIMI ELECTRONICS,...,1,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,NaN,Based On Sales Quotations 4108.,>7 Days
4,29,NaN,PWR-BTRY,60506,1662,4367.0,O,N,S22585,TRIP JACK PRIVATE LIMITED,...,1,0 to 1 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,06/08/2021,NaN,Based On Sales Quotations 4367.,>7 Days

In [4]:
from Operations.Column.column_operations import SortColumn

In [7]:
s = SortColumn(df, {
	"group" : "column operations",
	"task" : "sort",
	"config" : {
		"order" : "descending", #descending, ascending,
		"column" : "Vendor Name"
	}
})

In [8]:
s.sort()['detail']

,#,SBU - Head,SBU - Department,Document Entry,PO Number,PRF NO,Line Status,Canceled,Vendor Code,Vendor Name,...,Total Days,ageing,Target Days,Order Branch Name,Payment Terms Code,Part Code,Expected Date of Delivery,BuyBack delay,Remarks,Aging Range
10,15,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,ULTRATECH CEMENT LTD,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
21,21,NaN,PWR-UPS,60497,1653,4352.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
19,18,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
18,17,NaN,PWR-UPS,60476,1632,4237.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,Delivery Pending,Based On Sales Quotations 4237.,>7 Days
17,13,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
16,12,NaN,PWR-UPS,60450,1607,4199.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4199.,>7 Days
23,23,NaN,PWR-UPS,60498,1654,4353.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
24,24,NaN,PWR-BTRY,60498,1654,4353.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4353.,>7 Days
11,16,NaN,PWR-UPS,60475,1631,4232.0,O,N,S10639,ULTRATECH CEMENT LTD,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4232.,>7 Days
22,22,NaN,PWR-BTRY,60497,1653,4352.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,-1.0,Mumbai,- CREDIT DAYS -,NaN,06/11/2021,Delivery Pending,Based On Sales Quotations 4352.,>7 Days
25,25,NaN,PWR-UPS,60500,1656,4359.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
26,26,NaN,PWR-BTRY,60500,1656,4359.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4359.,>7 Days
27,27,NaN,PWR-UPS,60501,1657,4364.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
28,28,NaN,PWR-BTRY,60501,1657,4364.0,O,N,S10639,ULTRATECH CEMENT LTD,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/16/2021,NaN,Based On Sales Quotations 4364.,>7 Days
4,29,NaN,PWR-BTRY,60506,1662,4367.0,O,N,S22585,TRIP JACK PRIVATE LIMITED,...,1,0 to 1 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,06/08/2021,NaN,Based On Sales Quotations 4367.,>7 Days
29,30,NaN,NaN,60516,1672,NaN,O,N,S22462,TEAM ONE TECH SOLUTIONS LLP,...,0,0 to 1 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/07/2021,NaN,Based On Sales Quotations 4315.,>7 Days
3,11,NaN,PWR-BTRY,60427,1584,4108.0,O,N,S11146,SIMI ELECTRONICS,...,1,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,NaN,Based On Sales Quotations 4108.,>7 Days
9,2,NaN,PWR-BTRY,60328,1490,3611.0,O,N,S22112,SCHNEIDER ELECTRIC INDIA PVT LTD,...,7,5 to 7 Days,1.0,Mumbai,- CREDIT DAYS -,NaN,11/30/2020,Delivery Pending,Based On Sales Quotations 3611.,>7 Days
14,9,NaN,PWR-BTRY,60393,1550,4096.0,O,N,S22579,SAPAT GLOBAL HEALTH PVT LTD,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,Delivery Pending,Based On Sales Quotations 4096.,>7 Days
12,20,NaN,PWR-BTRY,60486,1642,4313.0,O,N,S12876,OBEROI CONSTRUCTIONS LIMITED,...,7,5 to 7 Days,5.0,Mumbai,- CREDIT DAYS -,NaN,06/12/2021,Delivery Pending,Based On Sales Quotations 4313.,>7 Days
5,6,NaN,PWR-BTRY,60374,1531,4040.0,O,N,S19423,NOCIL LIMITED,...,2,2 to 4 Days,-3.0,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4040.,>7 Days
15,10,NaN,PWR-BTRY,60403,1560,4138.0,O,N,S22536,MAHARASHTRA BORDER CHECK POST NETWORK LIMITED,...,0,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4138.,>7 Days
20,19,NaN,PWR-BTRY,60485,1641,4311.0,O,N,S22584,INTELLIGENCE BUREAU,...,0,0 to 1 Days,-2.0,Mumbai,- CREDIT DAYS -,NaN,06/05/2021,Delivery Pending,Based On Sales Quotations 4311.,>7 Days
7,7,NaN,PWR-BTRY,60389,1546,4027.0,O,N,S19854,ENCOMPASS EVENTS PVT LTD,...,4,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/03/2021,NaN,Based On Sales Quotations 4027.,>7 Days
2,4,NaN,PWR-BTRY,60348,1510,3958.0,O,N,S22574,DR FAROOQUI POLYCLINIC,...,1,0 to 1 Days,-4.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3958.,>7 Days
6,14,NaN,PWR-BTRY,60457,1614,4238.0,O,N,S19711,COMTEL INFOSYSTEMS PVT LTD,...,3,2 to 4 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,06/04/2021,NaN,Based On Sales Quotations 4238.,>7 Days
1,3,NaN,PWR-BTRY,60333,1495,3946.0,O,N,S20248,CHOKSEY CHEMICAL PVT LTD,...,1,0 to 1 Days,-5.0,Mumbai,- CREDIT DAYS -,NaN,06/02/2021,NaN,Based On Sales Quotations 3946.,>7 Days
0,1,NaN,PWR-BTRY,60318,75063,75322.0,O,N,S14470,BHILOSA INDUSTRIES PRIVATE LIMITED,...,1,0 to 1 Days,-5.0,Vapi,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 75322.,>7 Days
13,8,NaN,PWR-BTRY,60392,1549,4095.0,O,N,S12943,AVENUE SUPERMARTS LTD,...,0,0 to 1 Days,-4.0,Pune,- CREDIT DAYS -,NaN,06/03/2021,Delivery Pending,Based On Sales Quotations 4095.,>7 Days
8,5,NaN,PWR-BTRY,60360,1519,4010.0,O,N,S12943,AVENUE SUPERMARTS LTD,...,5,5 to 7 Days,NaN,Mumbai,- CREDIT DAYS -,NaN,05/27/2021,NaN,Based On Sales Quotations 4010.,>7 Days

In [1]:
import numpy as np
import pandas as pd

class ConditionUtility:
    
    def column_exists_validator(self, cond, df):
        print('I validate stuff')
        #if column doesn't exist 
        flag = True
        if cond[0]["middle"][1:-1] not in list(df.columns):
            flag = False
        try: 
            if cond[0]["left_cond"][0] == '#':
                if cond[0]["left_cond"][1:-1] not in list(df.columns):
                    flag = False
        except:
            print()
        
        try: 
            if cond[0]["right_cond"][0] == '#':
                if cond[0]["right_cond"][1:-1] not in list(df.columns):
                    flag = False
        except:
            print()
        
        if flag:
            return {"val" : flag, "details": ""}
        else:
            return {"val" : flag, "details":"column doesn't existing"}
        
    
    #Function to parse through the various conditions, and return the value that we need to add to 
    # he column, based on whichever condition it satisfies. 
    def parse_through_condition(self,cond,df):
        #Cond is a list of conditions, from which we need to pick up each condition, 
        #and evaluate the value based on that condition
        
        msg = self.column_exists_validator(cond, df)
        if not msg["val"]:
            return msg
        
        d_mid = df[cond[0]["middle"][1:-1]]
        if df[cond[0]["middle"][1:-1]].dtype == 'object':
            d_mid = d_mid.fillna(value="")
        if df[cond[0]["middle"][1:-1]].dtype == 'float':
            d_mid = d_mid.fillna(value=0.0)
        if df[cond[0]["middle"][1:-1]].dtype == 'int':
            d_mid = d_mid.fillna(value=0)
            
        middle_vals = list(d_mid)
        
        left_vals = []
        right_vals = []
        try:
            if cond[0]["left_cond"][0] == "#":
                d_left = df[cond[0]["left_cond"][1:-1]]
                if df[cond[0]["left_cond"][1:-1]].dtype == 'object':
                    d_left = d_left.fillna(value="")
                elif df[cond[0]["left_cond"][1:-1]].dtype == 'float':
                    d_left = d_left.fillna(value=0.0)
                elif df[cond[0]["left_cond"][1:-1]].dtype == 'int':
                    d_left = d_left.fillna(value=0)
                left_vals = list(d_left)
        except:
            print('')
        
        try:
            if cond[0]["right_cond"][0] == "#":
                d_right = df[cond[0]["right_cond"][1:-1]]
                if df[cond[0]["right_cond"][1:-1]].dtype == 'object':
                    d_right = d_right.fillna(value="")
                elif df[cond[0]["right_cond"][1:-1]].dtype == 'float':
                    d_right = d_right.fillna(value=0.0)
                elif df[cond[0]["right_cond"][1:-1]].dtype == 'int':
                    d_right = d_right.fillna(value=0)
                right_vals = list(d_right)
        except:
            print('')
        
            
        final = []
            
        for i in range(len(middle_vals)):
            cnt = 0
            for j in cond:
                left_condition=j["left_cond"]
                right_condition=j["right_cond"] 
                left_sign=j["left_sign"]
                right_sign=j["right_sign"]
                
                if left_vals != []:
                    left_condition = left_vals[i]
                if right_vals != []:
                    right_condition = right_vals[i]
                
                if left_condition == "NA":
                    left_condition = ""
                if right_condition == "NA":
                    right_condition = ""
                if left_sign == "NA":
                    left_sign = ""
                if right_sign == "NA":
                    right_sign = ""
                    
                middle = middle_vals[i]
                
                
                eval_str = self.get_eval_str(left_condition, left_sign, middle, right_sign, right_condition)
    
                if eval(eval_str):
                    final.append(j["val"])
                    break;
                cnt+=1
                if cnt == len(cond):
                    final.append("")
        return final
        
    #generating string for the er    
    def get_eval_str(self, lc, ls, v, rs, rc):
        return str(lc)+str(ls)+str(v)+str(rs)+str(rc)
               
        
    #adding column to dataframe
    def add_column(self, new_col_val, name, df, position):
        
        if position["deet"] == "after":
            loc = list(df.columns).index(position["col"]) + 1
            df.insert(loc, name, new_col_val)
        elif position["deet"] == "before":
            loc = list(df.columns).index(position["col"])
            df.insert(loc, name, new_col_val)
        elif position["deet"] == "beg":
            df.insert(0, name, new_col_val)
        elif position["deet"] == "end":
            df[name] = new_col_val
        
        return {"val" : True, "detail": df}

In [2]:
df = pd.read_csv('a.csv')

In [3]:
df

,#,SO Number,Document Internal ID,Posting Date,Execution Date,Customer Name,ItemName,Pending Qty,Unit Amt,Total Amt,Pending Days,Status,Sales Employee Name,SO Pending,Order Branch Name,Aging Range
0,1,6004,89728,07/20/2019,07/20/2019,MAHINDRA & MAHINDRA LIMITED,Installation Charges,1.0,20000.0,20000.0,688.0,NaN,Pankaj,Other Reason,Mumbai,>15 Days
1,2,8761,92651,09/06/2019,07/31/2021,VOLTEK ENGINEERING,LIEBERT 5 KVA LXI UPS,1.0,330000.0,330000.0,640.0,SO Pending for Material not -LIEBERT 5 KVA LXI...,Amar chavan,SO Pending for Material not available,Mumbai,>15 Days
2,3,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
3,4,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
4,5,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,773,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,LIEBERT GXT MT + CX 3 KVA XB 16A UPS SYSTEM,1.0,33000.0,33000.0,NaN,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
773,774,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,100AH/70AH X 06 Nos Rack,1.0,1000.0,1000.0,NaN,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
774,775,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,NYVIN Cable 12U,4.0,0.0,0.0,NaN,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
775,776,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,Links U-12 25 Inch,5.0,0.0,0.0,NaN,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
776,777,3487,127364,06/07/2021,NaN,MATCHWELL ENGINEERING PVT LTD,Comprehensive AMC,1.0,10500.0,10500.0,NaN,NaN,Sachin Kudale,Other Reason,Pune,>7 Days

In [4]:
c = Condition()

NameError: name 'Condition' is not defined

In [42]:
cond = {
	"group" : "column operations",
	"task" : "add",
	"name" : "Ageing",
	"position":{
		"col" : "Pending Days",
		"deet" : "after" #after, before, beg, end
	},
	"config" : {
		"condition": [{"left_cond":0, "left_sign":"<", "middle":"#Pendin Days#", "right_sign":"<=", "right_cond":10, "val":"0 to 10"}, {"left_cond":10, "left_sign":"<", "middle":"#Pending Days#", "right_sign":"<=", "right_cond":30, "val":"10 to 30"}, {"left_cond":30, "left_sign":"<", "middle":"#Pending Days#", "right_sign":"<=", "right_cond":45, "val":"30 to 45"}, {"left_cond":45, "left_sign":"<", "middle":"#Pending Days#", "right_sign":"NA", "right_cond":"NA", "val":"greater than 45"}],
		"math": "NA",
		"condmath": "NA"
	}
}

In [43]:
final = c.parse_through_condition(cond["config"]["condition"], df)
final

KeyError: 'Pendin Days'

In [31]:
d = c.add_column(final, cond["name"], df, cond["position"])
d['detail']

,#,SO Number,Document Internal ID,Posting Date,Execution Date,Customer Name,ItemName,Pending Qty,Unit Amt,Total Amt,Pending Days,Ageing,Status,Sales Employee Name,SO Pending,Order Branch Name,Aging Range
0,1,6004,89728,07/20/2019,07/20/2019,MAHINDRA & MAHINDRA LIMITED,Installation Charges,1.0,20000.0,20000.0,688.0,greater than 45,NaN,Pankaj,Other Reason,Mumbai,>15 Days
1,2,8761,92651,09/06/2019,07/31/2021,VOLTEK ENGINEERING,LIEBERT 5 KVA LXI UPS,1.0,330000.0,330000.0,640.0,greater than 45,SO Pending for Material not -LIEBERT 5 KVA LXI...,Amar chavan,SO Pending for Material not available,Mumbai,>15 Days
2,3,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,greater than 45,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
3,4,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,greater than 45,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
4,5,15140,99377,12/27/2019,06/30/2021,BALL BEVERAGE PACKING (INDIA) PVT LTD,Repair & Service Charges,1.0,10169.0,10169.0,528.0,greater than 45,THERMOGRAPHY PERIOD JUNE,Prashant Mohite,SO Pending Because of Special instrcutions fro...,Mumbai,>15 Days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,773,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,LIEBERT GXT MT + CX 3 KVA XB 16A UPS SYSTEM,1.0,33000.0,33000.0,NaN,,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
773,774,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,100AH/70AH X 06 Nos Rack,1.0,1000.0,1000.0,NaN,,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
774,775,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,NYVIN Cable 12U,4.0,0.0,0.0,NaN,,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
775,776,3483,127360,06/07/2021,05/31/2021,MECHATRONICS SYSTEMS PRIVATE LIMITED,Links U-12 25 Inch,5.0,0.0,0.0,NaN,,NaN,Sachin Kasture,Other Reason,Pune,>7 Days
776,777,3487,127364,06/07/2021,NaN,MATCHWELL ENGINEERING PVT LTD,Comprehensive AMC,1.0,10500.0,10500.0,NaN,,NaN,Sachin Kudale,Other Reason,Pune,>7 Days